[package]
name = "lbasedb"
version = "0.1.11"
edition = "2024"
authors = ["Alexander Khlebushchev"]
license = "MIT"
repository = "https://github.com/fomalhaut88/lbasedb"
description = "Low level DBMS in Rust focusing on datasets."

[dependencies]
base64 = "0.22.1"
futures = "0.3.32"
regex = "1.12.3"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.50.0", features = ["full"] }
